namespace BDInfoDataSubstractor
{
    internal class Program
    {
        private static readonly string _errorFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "errors.log");

        static async Task Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Tool expectes to provide text file(s) generated by bdinfo");
                return;
            }

            foreach (var file in args)
            {
                if (!File.Exists(file))
                {
                    continue;
                }

                try
                {
                    await DataContentManager.SubstractDataAsync(file);
                }
                catch (Exception ex)
                {
                    try
                    {
                        await File.AppendAllLinesAsync(_errorFile, [file, ex.Message, new string('=', 50)]);
                    }
                    catch
                    {
                        // kill
                    }
                }
            }
        }
    }
}
