name: Build x64

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
    
env:
  version: 2.0.6
  dotnetfolder: 'net9.0'
  bdinfo_key: "bdinfo"
  bdextract_key: "bdextractor"
  bdsubstractor_key: "bdinfodatasubstractor"
  

jobs:
  build_linux:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Remove organization git
      run: dotnet nuget remove source github
      continue-on-error: true
    #- name: Add organization git
    #  env: 
    #    NUGET_REPO_SECRET: ${{ secrets.NUGET_REPO_SECRET }}
    #  #run: dotnet nuget add source --username Sonic3R --password ${{ secrets.NUGET_REPO_SECRET }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dotnetcorecorner/index.json"
    #  run: dotnet nuget add source "https://nuget.pkg.github.com/dotnetcorecorner/index.json" --name github --username Sonic3R --password ${{ env.NUGET_REPO_SECRET }} --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore BDInfo.Core/BDInfo.Core.sln
    - name: Build against errors
      run: dotnet build BDInfo.Core/BDInfo.Core.sln --no-restore     
    - name: Create self-contained binary for BDInfo
      run: dotnet publish BDInfo.Core/BDInfo/BDInfo.csproj -c Release -r linux-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
    - name: Create self-contained binary for BDExtractor
      run: dotnet publish BDInfo.Core/BDExtractor/BDExtractor.csproj -c Release -r linux-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
    - name: Create self-contained binary for BDInfoDataSubstractor
      run: dotnet publish BDInfo.Core/BDInfoDataSubstractor/BDInfoDataSubstractor.csproj -c Release -r linux-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
      
    - name: BDInfo Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@591e9b128012d3328db6043d0d0266c3ac27f9b5
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdinfo_key }}_linux_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDInfo/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: BDExtractor ZIP release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdextract_key }}_linux_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDExtractor/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip

    - name: BDInfoDataSubstractor ZIP release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdsubstractor_key }}_linux_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDInfoDataSubstractor/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: linux-${{ env.version }}
        release_name: Release Linux x64 ${{ env.version }}
        draft: false
        prerelease: false
        
    - name: Upload BDInfo
      id: upload-release-asset-bdinfo
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDInfo/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/${{ env.bdinfo_key }}_linux_v${{ env.version }}.zip
        asset_name: ${{ env.bdinfo_key }}_linux_v${{ env.version }}.zip
        asset_content_type: application/zip
        
    - name: Upload BDExtractor
      id: upload-release-asset-bdextractor
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDExtractor/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/${{ env.bdextract_key }}_linux_v${{ env.version }}.zip
        asset_name: ${{ env.bdextract_key }}_linux_v${{ env.version }}.zip
        asset_content_type: application/zip

    - name: Upload BDInfoDataSubstractor
      id: upload-release-asset-bdinfodatasubstractor
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDInfoDataSubstractor/bin/Release/${{ env.dotnetfolder }}/linux-x64/publish/${{ env.bdsubstractor_key }}_linux_v${{ env.version }}.zip
        asset_name: ${{ env.bdsubstractor_key }}_linux_v${{ env.version }}.zip
        asset_content_type: application/zip


  build_windows:

    runs-on: windows-latest
    needs: [build_linux]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Remove organization git
      run: dotnet nuget remove source github
      continue-on-error: true
    #- name: Add organization git
    #  env: 
    #    NUGET_REPO_SECRET: ${{ secrets.NUGET_REPO_SECRET }}
    #  run: dotnet nuget add source "https://nuget.pkg.github.com/dotnetcorecorner/index.json" --name github --username Sonic3R --password ${{ env.NUGET_REPO_SECRET }} --store-password-in-clear-text
    - name: Restore dependencies
      run: dotnet restore BDInfo.Core/BDInfo.Core.sln
    - name: Build against errors
      run: dotnet build BDInfo.Core/BDInfo.Core.sln --no-restore     
    - name: Create self-contained binary for BDInfo
      run: dotnet publish BDInfo.Core/BDInfo/BDInfo.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
    - name: Create self-contained binary for BDExtractor
      run: dotnet publish BDInfo.Core/BDExtractor/BDExtractor.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
    - name: Create self-contained binary for BDInfoDataSubstractor
      run: dotnet publish BDInfo.Core/BDInfoDataSubstractor/BDInfoDataSubstractor.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained
      
    - name: BDInfo Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@591e9b128012d3328db6043d0d0266c3ac27f9b5
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdinfo_key }}_win_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDInfo/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: BDExtractor ZIP release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdextract_key }}_win_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDExtractor/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip

    - name: BDInfoDataSubstractor ZIP release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: ${{ env.bdsubstractor_key }}_win_v${{ env.version }}.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: BDInfo.Core/BDInfoDataSubstractor/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/
        # List of excluded files / directories
        #exclusions: # optional, default is 
        # Tool to use for archiving
        type: zip
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: win-${{ env.version }}
        release_name: Release Windows x64 ${{ env.version }}
        draft: false
        prerelease: false
        
    - name: Upload BDInfo
      id: upload-release-asset-bdinfo
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDInfo/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/${{ env.bdinfo_key }}_win_v${{ env.version }}.zip
        asset_name: ${{ env.bdinfo_key }}_win_v${{ env.version }}.zip
        asset_content_type: application/zip
        
    - name: Upload BDExtractor
      id: upload-release-asset-bdextractor
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDExtractor/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/${{ env.bdextract_key }}_win_v${{ env.version }}.zip
        asset_name: ${{ env.bdextract_key }}_win_v${{ env.version }}.zip
        asset_content_type: application/zip

    - name: Upload BDInfoDataSubstractor
      id: upload-release-asset-bdinfodatasubstractor
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: BDInfo.Core/BDInfoDataSubstractor/bin/Release/${{ env.dotnetfolder }}/win-x64/publish/${{ env.bdsubstractor_key }}_win_v${{ env.version }}.zip
        asset_name: ${{ env.bdsubstractor_key }}_win_v${{ env.version }}.zip
        asset_content_type: application/zip
